# This workflow will deploy the updated cloud environment to the staging environment
name: Build the image

on: 
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t coaze/pulumi-dotnet-ci:vbeta .